//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_voting {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("e_voting.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Program Hakkında benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string _programmeinfo {
            get {
                return ResourceManager.GetString("_programmeinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   insert into kod(isim,mail,kod) values (@isim,@mail,@kod) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string addcode {
            get {
                return ResourceManager.GetString("addcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   insert into tile3(isim,kod,oy) values (@isim,@kod,@oy) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string addtile3 {
            get {
                return ResourceManager.GetString("addtile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   insert into veri(isim,mail) values (@isim,@mail) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string addveri {
            get {
                return ResourceManager.GetString("addveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alınan Doğrulama Kod. Getir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_getcode {
            get {
                return ResourceManager.GetString("btn_getcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy Vermek İsteyenleri Getir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_getmaillist {
            get {
                return ResourceManager.GetString("btn_getmaillist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hadi Seçim Zamanı! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_letsvote {
            get {
                return ResourceManager.GetString("btn_letsvote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy Sayımı Oluştur benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_newvotecount {
            get {
                return ResourceManager.GetString("btn_newvotecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodlarını Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_sendcode {
            get {
                return ResourceManager.GetString("btn_sendcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgileri Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string btn_showinfo {
            get {
                return ResourceManager.GetString("btn_showinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adaylar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string candidates {
            get {
                return ResourceManager.GetString("candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Adresi Onaylıyorum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_btn_acceptnewaddress {
            get {
                return ResourceManager.GetString("changingaddress_btn_acceptnewaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adreste Düzenleme Yapabilmek için Doğrulama Kodu Gönder benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_btn_sendingcode {
            get {
                return ResourceManager.GetString("changingaddress_btn_sendingcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kodu Onaylıyorum benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_btn_verifycode {
            get {
                return ResourceManager.GetString("changingaddress_btn_verifycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mevcut Adres benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_lbl_title {
            get {
                return ResourceManager.GetString("changingaddress_lbl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mail Adresi: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_lbl_titleaddress {
            get {
                return ResourceManager.GetString("changingaddress_lbl_titleaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string changingaddress_lbl_titlecode {
            get {
                return ResourceManager.GetString("changingaddress_lbl_titlecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kontrol ediliyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string checking {
            get {
                return ResourceManager.GetString("checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string code {
            get {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string code_ {
            get {
                return ResourceManager.GetString("code_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select * from kod benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string codeselect {
            get {
                return ResourceManager.GetString("codeselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu Gönderimi Kontrolü benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string controlofcode {
            get {
                return ResourceManager.GetString("controlofcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı mail adresi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string couldntfindmailaddress {
            get {
                return ResourceManager.GetString("couldntfindmailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı doğrulama kodu bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string couldntfindvalidcode {
            get {
                return ResourceManager.GetString("couldntfindvalidcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete from veri where mail=@mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string deletemail {
            get {
                return ResourceManager.GetString("deletemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete from tile3 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string deletetile3 {
            get {
                return ResourceManager.GetString("deletetile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   delete from veri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string deleteveri {
            get {
                return ResourceManager.GetString("deleteveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-US benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EN benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email gönderme işlemi başlatılmadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string errormail {
            get {
                return ResourceManager.GetString("errormail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Başlatılmayan İşlem benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string errorprocess {
            get {
                return ResourceManager.GetString("errorprocess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Dosyası |*.xlsx| Excel Dosyası|*.xls benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string excelfilter {
            get {
                return ResourceManager.GetString("excelfilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Veri Excel&apos;ini seçiniz... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string exceltitle {
            get {
                return ResourceManager.GetString("exceltitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adreslerini Gizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hideerrorlist {
            get {
                return ResourceManager.GetString("hideerrorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Doğrulama Kodlarını Gizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hidenotvalidcode {
            get {
                return ResourceManager.GetString("hidenotvalidcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hacettepe Üniversitesi Psikoloji Topluluğu (HÜPT) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title {
            get {
                return ResourceManager.GetString("hupt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HÜPT - Oy Doğrulama Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title2 {
            get {
                return ResourceManager.GetString("hupt_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merhaba Sevgili  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title3 {
            get {
                return ResourceManager.GetString("hupt_title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HÜPT seçimlerinde oy kullanabilmeniz için gereken doğrulama kodu:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title4 {
            get {
                return ResourceManager.GetString("hupt_title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy kullanacağınız için çok teşekkür ederiz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string hupt_title5 {
            get {
                return ResourceManager.GetString("hupt_title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bilgilendirme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string information {
            get {
                return ResourceManager.GetString("information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod Gönderen Mail Adresini Düzenlemek için Tıklayınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_editingaddress {
            get {
                return ResourceManager.GetString("lbl_editingaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;Kapalı oy açık sayım&quot; usülüne göre seçim gerçekleştirileceği için burada herhangi bir şekilde bilgiler gösterilmeyecektir.
        ///
        ///Seçim sonuçlarına gelebilecek olan olası itirazlar için &quot;Bilgileri Göster&quot; butonuna basılarak oy verenlerin &quot;kişisel bilgileri hariç&quot; diğer bilgiler görülebilecektir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_info {
            get {
                return ResourceManager.GetString("lbl_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Program Hakkında Detaylı Bilgi Almak için Tıklayınız benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_programinfo {
            get {
                return ResourceManager.GetString("lbl_programinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mailler Gönderiliyor... Lütfen Programı Kapatmayınız... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_sendcodeinfo {
            get {
                return ResourceManager.GetString("lbl_sendcodeinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adreslerini Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_showerrorlist {
            get {
                return ResourceManager.GetString("lbl_showerrorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Doğrulama Kodlarını Gizle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_shownotvalidcode {
            get {
                return ResourceManager.GetString("lbl_shownotvalidcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Aşama - Doğrulama Kodu Gönderimleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_tier1 {
            get {
                return ResourceManager.GetString("lbl_tier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   2. Aşama - Doğrulama Kodu Kontrolleri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_tier2 {
            get {
                return ResourceManager.GetString("lbl_tier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   3. Aşama - Oyların Sayımı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_tier3 {
            get {
                return ResourceManager.GetString("lbl_tier3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod Gönderilebilecek Toplam Kişi Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_totalpeople {
            get {
                return ResourceManager.GetString("lbl_totalpeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kod Alınan Toplam Kişi Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_totalpeoplereceivecode {
            get {
                return ResourceManager.GetString("lbl_totalpeoplereceivecode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçerli Toplam Kişi Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_totalpeoplereceivecodewithvalid {
            get {
                return ResourceManager.GetString("lbl_totalpeoplereceivecodewithvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geçerli Toplam Kişi Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_totalvalidatepeople {
            get {
                return ResourceManager.GetString("lbl_totalvalidatepeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Toplam Oy Sayısı: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_votecount {
            get {
                return ResourceManager.GetString("lbl_votecount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oylama Tablosu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lbl_votefinaltable {
            get {
                return ResourceManager.GetString("lbl_votefinaltable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1. Program Hakkında Dikkat Edilmesi Gerekenler
        ///
        ///* Seçim güvenliği gereği bu programda sadece &quot;....@hacettepe.edu.tr&quot; ile oluşan mail adreslerine doğrulama kodu gönderilebilecektir. Gmail, Hotmail, Yahoo, Outloook gibi servis sağlayıcılarının mail adreslerine doğrulama kodu gönderilmeyecektir.
        ///
        ///* Oy kullanmak isteyen kişileri yüklerken excel dosyanızda sadece isim ve maillerin yer aldığı sütunların kalmasına ve başka herhangi bir sütun olmamasına dikkat ediniz. Ayrıca excelde ilk sütun(A) isimlere, ikinci sü [dizenin kalan bölümü kesildi]&quot;; benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblinfoprogramme {
            get {
                return ResourceManager.GetString("lblinfoprogramme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tüm Doğrulama Kodları Başarı Bir Şekilde Gönderildi :)) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lblinfowithload {
            get {
                return ResourceManager.GetString("lblinfowithload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yükleniyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı mail adresi bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_errorlist1 {
            get {
                return ResourceManager.GetString("lst_errorlist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 adet hatalı mail adresi çıkarıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_errorlist2 {
            get {
                return ResourceManager.GetString("lst_errorlist2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adet hatalı mail adresleri çıkarıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_errorlist3 {
            get {
                return ResourceManager.GetString("lst_errorlist3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı doğrulama kodu bulunamadı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_notvalidcode1 {
            get {
                return ResourceManager.GetString("lst_notvalidcode1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   1 adet hatalı doğrulama kodu çıkarıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_notvalidcode2 {
            get {
                return ResourceManager.GetString("lst_notvalidcode2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adet hatalı doğrulama kodu çıkarıldı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string lst_notvalidcode3 {
            get {
                return ResourceManager.GetString("lst_notvalidcode3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @mail benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mail_ {
            get {
                return ResourceManager.GetString("mail_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yüklemiş olduğunuz excelde herhangi bir veri bulunamadı ya da veriler içinden geçerli olan herhangi bir doğrulama kodu bulunamadı. Lütfen excel dosyanızın içinde verilerin olduğundan ve var olan doğrulama kodlarının doğru olduğundan emin olunuz ve ardından tekrar deneyiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mb_error {
            get {
                return ResourceManager.GetString("mb_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hata benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string mb_hata {
            get {
                return ResourceManager.GetString("mb_hata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Herhangi bir işlem yapılmadı. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagecancel {
            get {
                return ResourceManager.GetString("messagecancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu Onayı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messageconfirmcode {
            get {
                return ResourceManager.GetString("messageconfirmcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı doğrulama kodu girildi. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messageerrorcode {
            get {
                return ResourceManager.GetString("messageerrorcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adres Düzenleme benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagemailto {
            get {
                return ResourceManager.GetString("messagemailto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu Gönderimi benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesendingcode {
            get {
                return ResourceManager.GetString("messagesendingcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Değişiklik başarıyla kaydedildi. Doğrulama kodları bundan sonra  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccesspart1 {
            get {
                return ResourceManager.GetString("messagesuccesspart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///    adresinden gönderilecektir. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccesspart2 {
            get {
                return ResourceManager.GetString("messagesuccesspart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Başarılı. Lütfen size gönderilen doğrulama kodunu aktif olmuş olan kutucuğa yazınız ve onaylayınız. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccesssending {
            get {
                return ResourceManager.GetString("messagesuccesssending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlem Başarılı. Hesapta düzenleme işlemlerinizi yapmaya başlayabilirsiniz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messagesuccessverify {
            get {
                return ResourceManager.GetString("messagesuccessverify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   İşlemi Başlatmak İstediğinize Emin Misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string messsagestart {
            get {
                return ResourceManager.GetString("messsagestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   isim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @isim benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string name_ {
            get {
                return ResourceManager.GetString("name_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   0 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string number {
            get {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider=Microsoft.ACE.Oledb.12.0;Data Source=kod.accdb;Persist Security Info=True benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string oledbconcode {
            get {
                return ResourceManager.GetString("oledbconcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider=Microsoft.ACE.OLEDB.12.0;Data Source=tile3.accdb;Persist Security Info=True benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string oledbcontile3 {
            get {
                return ResourceManager.GetString("oledbcontile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Provider=Microsoft.ACE.OLEDB.12.0;Data Source=veri.accdb;Persist Security Info=True benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string oledbconveri {
            get {
                return ResourceManager.GetString("oledbconveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hazırlanıyor... benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string preparing {
            get {
                return ResourceManager.GetString("preparing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select * from tile3 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string selecttile3 {
            get {
                return ResourceManager.GetString("selecttile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select * from veri benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string selectveri {
            get {
                return ResourceManager.GetString("selectveri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama kodlarını toplu bir şekilde e-mail göndermek istediğinize emin misiniz? benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string sendingcodemessage {
            get {
                return ResourceManager.GetString("sendingcodemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Mail Adreslerini Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string showerrorlist {
            get {
                return ResourceManager.GetString("showerrorlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hatalı Doğrulama Kodlarını Göster benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string shownotvalidcode {
            get {
                return ResourceManager.GetString("shownotvalidcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   smtp.gmail.com benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string smtp {
            get {
                return ResourceManager.GetString("smtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ----------------------- benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string symbol {
            get {
                return ResourceManager.GetString("symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   %10 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tenpercentage {
            get {
                return ResourceManager.GetString("tenpercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tile3 benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tile3 {
            get {
                return ResourceManager.GetString("tile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oylama Vakti benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string timeofcount {
            get {
                return ResourceManager.GetString("timeofcount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tr-TR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string turkce {
            get {
                return ResourceManager.GetString("turkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Doğrulama Kodu benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string verificationcode {
            get {
                return ResourceManager.GetString("verificationcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @oy benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string vote_ {
            get {
                return ResourceManager.GetString("vote_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy sayım işlemi tamamlanmıştır. Kazanan aday/adaylarımızı tebrik ederiz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string votecountinfo {
            get {
                return ResourceManager.GetString("votecountinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy Sayıları benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string votecounts {
            get {
                return ResourceManager.GetString("votecounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oy Sayım Bitmiştir benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string voteinfo {
            get {
                return ResourceManager.GetString("voteinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yeni Oy Sayımı için program hazır. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string votemessage {
            get {
                return ResourceManager.GetString("votemessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oylar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string votes {
            get {
                return ResourceManager.GetString("votes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Oylar Başarılı Bir Şekilde Sisteme Alınmıştır. Oy Sayım İşlemine Geçebiliriz. benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string votetime {
            get {
                return ResourceManager.GetString("votetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sayfa Adı benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string wordname {
            get {
                return ResourceManager.GetString("wordname", resourceCulture);
            }
        }
    }
}
